'use client'; import type { InheritedComponentProps } from '../types'; 
import type { ReactNode } from 'react';
import { useEffect, useState } from 'react';
import type { ViewProps } from 'react-native';
import { AccessibilityInfo, Animated, Easing } from 'react-native';
/** Props for an entrance animation that honors reduced-motion preferences. */ export type MotionViewProps = InheritedComponentProps<ViewProps & { children?: ReactNode; delay?: number; distance?: number; duration?: number; }>;
/** Props for an animated percentage-width indicator. */ export type MotionProgressProps = InheritedComponentProps<ViewProps & { duration?: number; value: number; }>;
function clampPercentage(value: number) { if (!Number.isFinite(value)) return 0; return Math.min(100, Math.max(0, value)); }
/** Reveals children with a subtle translate, scale, and opacity animation. */ export function MotionView({ children, delay = 0, distance = 12, duration = 280, style, ...props }: MotionViewProps) { const [progress] = useState(() => new Animated.Value(0)); useEffect(() => { let active = true; let animation: Animated.CompositeAnimation | undefined; void AccessibilityInfo.isReduceMotionEnabled().then((reducedMotion) => { if (!active) return; if (reducedMotion) { progress.setValue(1); return; } animation = Animated.timing(progress, { delay, duration, easing: Easing.out(Easing.cubic), toValue: 1, useNativeDriver: true, }); animation.start(); }); return () => { active = false; animation?.stop(); }; }, [delay, duration, progress]); return (<Animated.View style={[ { opacity: progress, transform: [ { translateY: progress.interpolate({ inputRange: [0, 1], outputRange: [distance, 0], }), }, { scale: progress.interpolate({ inputRange: [0, 1], outputRange: [0.985, 1], }), }, ], }, style, ]} {...props}>{children}</Animated.View>); }
/** Animates a view's width to a clamped percentage. */ export function MotionProgress({ duration = 520, style, value, ...props }: MotionProgressProps) { const [progress] = useState(() => new Animated.Value(0)); useEffect(() => { let active = true; let animation: Animated.CompositeAnimation | undefined; const nextValue = clampPercentage(value); void AccessibilityInfo.isReduceMotionEnabled().then((reducedMotion) => { if (!active) return; if (reducedMotion) { progress.setValue(nextValue); return; } animation = Animated.timing(progress, { duration, easing: Easing.out(Easing.cubic), toValue: nextValue, useNativeDriver: false, }); animation.start(); }); return () => { active = false; animation?.stop(); }; }, [duration, progress, value]); return (<Animated.View style={[ { width: progress.interpolate({ inputRange: [0, 100], outputRange: ['0%', '100%'], }), }, style, ]} {...props}/>); }
