import type { InheritedComponentProps } from '../types'; import type { ReactNode } from 'react'; import { forwardRef } from 'react'; import type { TextProps, ViewProps } from 'react-native';
import { Text, View } from 'react-native'; import { cn } from '../core/cn'; import { elevatedSurfaceClassName } from '../core/styles';
/** Props for the unstyled layout primitive. */ export type BoxProps = InheritedComponentProps<ViewProps & { children?: ReactNode; className?: string; }>; /** Unstyled ref-forwarding layout primitive. */ 
/** Public box component or design-system primitive. */
export const Box = forwardRef<View, BoxProps>(function Box({ children, className, ...props }, ref) { return (<View className={className} ref={ref} {...props}>{children}</View>); }); const containerWidths = { lg: 'max-w-5xl', md: 'max-w-3xl', sm: 'max-w-xl', xl: 'max-w-7xl', } as const;
/** Props for a centered, width-constrained container. */ export type ContainerProps = InheritedComponentProps<BoxProps & { maxWidth?: keyof typeof containerWidths; }>; /** Centers content within a responsive maximum width. */ 
/** Renders the container component. */
export function Container({ children, className, maxWidth = 'lg', ...props }: ContainerProps) { return (<View className={cn('mx-auto w-full px-4 sm:px-6', containerWidths[maxWidth], className)} {...props}>{children}</View>); } const elevationClasses = { 0: '', 1: 'shadow-sm', 2: 'shadow-md', 3: 'shadow-lg', 4: 'shadow-xl', } as const;
/** Props for an elevated or outlined content surface. */ export type PaperProps = InheritedComponentProps<BoxProps & { elevation?: keyof typeof elevationClasses; variant?: 'elevated' | 'outlined'; }>; /** Renders content on a configurable paper surface. */ 
/** Public paper component or design-system primitive. */
export const Paper = forwardRef<View, PaperProps>(function Paper({ children, className, elevation = 1, variant = 'elevated', ...props }, ref) { return (<View className={cn('relative overflow-hidden rounded-[28px] p-5 sm:p-6', elevatedSurfaceClassName, variant === 'outlined' && 'border border-slate-200 dark:border-slate-800', variant === 'elevated' && elevationClasses[elevation], variant === 'outlined' && 'shadow-none web:hover:shadow-md', className)} ref={ref} {...props}>{children}</View>); }); /** Props for a responsive grid container. */ 
/** Props accepted by the grid component. */
export type GridProps = InheritedComponentProps<BoxProps & { columns?: 1 | 2 | 3 | 4; }>;
const gridClasses = { 1: '', 2: 'sm:flex-row sm:flex-wrap', 3: 'sm:flex-row sm:flex-wrap lg:flex-nowrap', 4: 'sm:flex-row sm:flex-wrap xl:flex-nowrap', } as const; /** Arranges children in a responsive grid. */ 
/** Renders the grid component. */
export function Grid({ children, className, columns = 2, ...props }: GridProps) { return (<View className={cn('gap-4', gridClasses[columns], className)} {...props}>{children}</View>); } /** Flexible child for use inside a Grid. */ 
/** Public grid item component or design-system primitive. */
export const GridItem = forwardRef<View, BoxProps>(function GridItem({ children, className, ...props }, ref) { return (<View className={cn('min-w-0 flex-1', className)} ref={ref} {...props}>{children}</View>); });
const typographyClasses = { body1: 'text-base leading-7 text-slate-700 antialiased dark:text-slate-200', body2: 'text-sm leading-6 text-slate-600 dark:text-slate-300', button: 'text-sm font-bold uppercase tracking-[0.5px]', caption: 'text-xs leading-5 text-slate-500 dark:text-slate-400', h1: 'text-4xl font-black leading-[46px] tracking-[-1px] text-slate-950 antialiased dark:text-white sm:text-5xl sm:leading-[58px]', h2: 'text-3xl font-black leading-10 tracking-[-0.75px] text-slate-950 antialiased dark:text-white sm:text-4xl', h3: 'text-2xl font-black leading-8 text-slate-950 dark:text-white sm:text-3xl', h4: 'text-xl font-black leading-7 text-slate-950 dark:text-white sm:text-2xl', h5: 'text-lg font-black text-slate-950 dark:text-white', h6: 'text-base font-black text-slate-950 dark:text-white', overline: 'text-[10px] font-black uppercase tracking-[2px] text-brand-600 dark:text-brand-300', subtitle1: 'text-base font-bold text-slate-700 dark:text-slate-200', subtitle2: 'text-sm font-bold text-slate-600 dark:text-slate-300', } as const; /** Props for a semantic design-system text variant. */ 
/** Props accepted by the typography component. */
export type TypographyProps = InheritedComponentProps<TextProps & { children?: ReactNode; className?: string; variant?: keyof typeof typographyClasses; }>; /** Renders text using a semantic typography token. */ 
/** Renders the typography component. */
export function Typography({ children, className, variant = 'body1', ...props }: TypographyProps) { return (<Text className={cn(typographyClasses[variant], className)} {...props}> {children} </Text>); }
