import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../global.css"
/**
 * @constant geistSans
 * @description Load Geist Sans font with CSS variable.
 */
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// /**
//  * @constant geistMono
//  * @description Load Geist Mono font with CSS variable.
//  */
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

/**
 * @constant metadata
 * @description Default metadata for the app.
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * @component RootLayout
 * @description Root layout for the entire application.
 * Handles global providers and font setup.
 * @param {Object} props - Component props.
 * @param {React.ReactNode} props.children - Page content.
 * @returns {JSX.Element} Layout structure.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        /**
         * @property className
         * @description Apply loaded font variables and enable antialiasing.
         */
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}