import type { Metadata } from 'next';
import '../scss/global.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import React from 'react';
/**
 *
 */
export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html>
        <body>{children}</body>
      </html>
    </>
  );
}
