'use client'; import type { InheritedComponentProps } from '../types';  import type { ReactNode } from 'react';
import { useEffect } from 'react'; import { Modal as NativeModal, Pressable, Text, View } from 'react-native';
import { cn } from '../core/cn'; import { MotionView } from '../core/motion';

/** Renders the backdrop component. */
export function Backdrop({ children, onPress, open }: InheritedComponentProps<{ children?: ReactNode; onPress?: () => void; open: boolean; }>) { if (!open) return null; return (<NativeModal animationType="fade" onRequestClose={onPress} transparent visible><View className="flex-1 items-center justify-center bg-slate-950/70 px-5"><Pressable accessibilityLabel="Close overlay" className="absolute inset-0" onPress={onPress}/>{children}</View></NativeModal>); } 
/** Props accepted by the dialog component. */
export type DialogProps = InheritedComponentProps<{ actions?: ReactNode; children?: ReactNode; onClose: () => void; open: boolean; title?: string; }>;

/** Renders the dialog component. */
export function Dialog({ actions, children, onClose, open, title }: DialogProps) { return (<NativeModal animationType="fade" onRequestClose={onClose} transparent visible={open}><View className="flex-1 items-center justify-center bg-slate-950/70 px-5"><Pressable accessibilityLabel="Close dialog" className="absolute inset-0" onPress={onClose}/><MotionView accessibilityViewIsModal className="w-full max-w-lg overflow-hidden rounded-[30px] border border-white/60 bg-white p-6 shadow-xl dark:border-slate-700 dark:bg-slate-900"><View className="absolute left-6 right-6 top-0 h-1 rounded-b-full bg-brand-500"/>{title ? <Text className="pr-8 text-xl font-black tracking-tight text-slate-950 dark:text-white">{title}</Text> : null}<View className="py-5">{children}</View>{actions ? <View className="flex-row flex-wrap justify-end gap-3 border-t border-slate-100 pt-4 dark:border-slate-800">{actions}</View> : null}</MotionView></View></NativeModal>); } const snackbarPositionClasses = { bottom: 'justify-end pb-8', top: 'justify-start pt-8', } as const;

/** Props accepted by the snackbar component. */
export type SnackbarProps = InheritedComponentProps<{ action?: ReactNode; autoHideDuration?: number; message: string; onClose: () => void; open: boolean; position?: keyof typeof snackbarPositionClasses; }>; 
/** Renders the snackbar component. */
export function Snackbar({ action, autoHideDuration, message, onClose, open, position = 'bottom', }: SnackbarProps) { useEffect(() => { if (!open || !autoHideDuration) return undefined; const timeout = setTimeout(onClose, autoHideDuration); return () => clearTimeout(timeout); }, [autoHideDuration, onClose, open]); return (<NativeModal animationType="fade" onRequestClose={onClose} transparent visible={open}><View className={cn('flex-1 items-center px-4', snackbarPositionClasses[position])} pointerEvents="box-none"><MotionView accessibilityRole="alert" className="w-full max-w-lg flex-row items-center rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 shadow-xl dark:border-slate-200 dark:bg-white" distance={position === 'bottom' ? 18 : -18}><View className="mr-3 h-2.5 w-2.5 rounded-full bg-brand-400"/><Text className="min-w-0 flex-1 text-sm font-semibold text-white dark:text-slate-950">{message}</Text>{action ? <View className="ml-3">{action}</View> : null}</MotionView></View></NativeModal>); }
