'use client'; import type { InheritedComponentProps } from '../types';  import { useState } from 'react';
import type { ReactNode } from 'react'; import { Pressable, RefreshControl, ScrollView, Text, View } from 'react-native';
import { cn } from '../core/cn'; import { SearchBar } from '../forms/BasicInputs';
import type { DataGridColumn, DataGridRow } from './model/dataGrid'; import { useDataGridController } from './presentation/useDataGridController';

/** Renders the data grid component. */
export function DataGrid({ columns, pageSize = 4, rows }: InheritedComponentProps<{ columns: DataGridColumn[]; pageSize?: number; rows: DataGridRow[]; }>) { const { filteredRows, page, query, setPage, sort, toggleSort, totalPages, updateQuery, visibleRows } = useDataGridController(rows, pageSize); return (<View className="overflow-hidden rounded-3xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><View className="gap-3 border-b border-slate-200 p-4 dark:border-slate-700 sm:flex-row sm:items-center sm:justify-between"><View><Text className="font-black text-slate-950 dark:text-white">Data grid</Text><Text className="mt-1 text-xs text-slate-500 dark:text-slate-400">Search, sort and paginate</Text></View><SearchBar className="sm:w-64" onChangeText={updateQuery} value={query}/></View><ScrollView horizontal><View className="min-w-[680px] flex-1"><View accessibilityRole="header" className="flex-row bg-slate-100 dark:bg-slate-800">{columns.map((column) => (<Pressable className="min-h-12 flex-1 flex-row items-center px-4 web:cursor-pointer" disabled={!column.sortable} key={column.key} onPress={() => toggleSort(column.key)}><Text className="text-xs font-black uppercase tracking-[1px] text-slate-600 dark:text-slate-300">{column.label}</Text>{sort?.key === column.key ? <Text className="ml-2 text-brand-600 dark:text-brand-300">{sort.direction === 'asc' ? '↑' : '↓'}</Text> : null}</Pressable>))}</View>{visibleRows.map((row) => (<View className="min-h-14 flex-row items-center border-t border-slate-100 dark:border-slate-800" key={row.id}>{columns.map((column) =><Text className={cn('flex-1 px-4 text-sm text-slate-700 dark:text-slate-200', column.numeric && 'text-right font-mono')} key={column.key}>{String(row[column.key] ?? '')}</Text>)}</View>))}{!visibleRows.length ? <View className="items-center p-8"><Text className="font-semibold text-slate-400">No matching rows</Text></View> : null}</View></ScrollView><View className="flex-row items-center justify-between border-t border-slate-200 p-4 dark:border-slate-700"><Text className="text-xs font-semibold text-slate-500 dark:text-slate-400">{filteredRows.length} rows · Page {Math.min(page, totalPages)} of {totalPages}</Text><View className="flex-row gap-2"><Pressable className="rounded-xl border border-slate-200 px-3 py-2 web:cursor-pointer dark:border-slate-700" disabled={page <= 1} onPress={() => setPage((current) => Math.max(1, current - 1))}><Text className="font-black text-slate-600 dark:text-slate-300">←</Text></Pressable><Pressable className="rounded-xl bg-brand-600 px-3 py-2 web:cursor-pointer" disabled={page >= totalPages} onPress={() => setPage((current) => Math.min(totalPages, current + 1))}><Text className="font-black text-white">→</Text></Pressable></View></View></View>); } 
/** Public contract for tree node. */
export type TreeNode = { children?: readonly TreeNode[]; id: string; label: string; note?: string; };
function TreeNodeView({ depth, expanded, node, onToggle }: InheritedComponentProps<{ depth: number; expanded: Set<string>; node: TreeNode; onToggle: (id: string) => void; }>) { const open = expanded.has(node.id); const hasChildren = Boolean(node.children?.length); const indentClasses = ['pl-0', 'pl-5', 'pl-10', 'pl-14']; return (<View><Pressable accessibilityRole="button" accessibilityState={{ expanded: hasChildren ? open : undefined }} className={cn('min-h-12 flex-row items-center rounded-xl pr-3 web:cursor-pointer web:hover:bg-slate-100 dark:web:hover:bg-slate-800', indentClasses[Math.min(depth, indentClasses.length - 1)])} onPress={() => hasChildren && onToggle(node.id)}><Text className="w-7 text-center font-black text-brand-600 dark:text-brand-300">{hasChildren ? (open ? '−' : '+') : '•'}</Text><View className="min-w-0 flex-1"><Text className="font-bold text-slate-800 dark:text-slate-100">{node.label}</Text>{node.note ? <Text className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{node.note}</Text> : null}</View></Pressable>{open ? node.children?.map((child) =><TreeNodeView depth={depth + 1} expanded={expanded} key={child.id} node={child} onToggle={onToggle}/>) : null}</View>); } 
/** Renders the tree view component. */
export function TreeView({ nodes }: InheritedComponentProps<{ nodes: readonly TreeNode[]; }>) { const [expanded, setExpanded] = useState<Set<string>>(() => new Set(nodes.slice(0, 1).map((node) => node.id))); const toggle = (id: string) => setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); return <View className="rounded-3xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900">{nodes.map((node) =><TreeNodeView depth={0} expanded={expanded} key={node.id} node={node} onToggle={toggle}/>)}</View>; }

/** Public contract for transfer item. */
export type TransferItem = { id: string; label: string; }; function TransferColumn({ items, onToggle, selected, title }: InheritedComponentProps<{ items: TransferItem[]; onToggle: (id: string) => void; selected: string[]; title: string; }>) { return <View className="min-w-52 flex-1 overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-700"><Text className="bg-slate-100 px-4 py-3 font-black text-slate-800 dark:bg-slate-800 dark:text-white">{title}</Text>{items.map((item) =><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selected.includes(item.id) }} className={cn('min-h-11 justify-center border-t border-slate-100 px-4 web:cursor-pointer dark:border-slate-800', selected.includes(item.id) && 'bg-brand-50 dark:bg-brand-950')} key={item.id} onPress={() => onToggle(item.id)}><Text className="font-semibold text-slate-700 dark:text-slate-200">{selected.includes(item.id) ? '✓ ' : ''}{item.label}</Text></Pressable>)}</View>; }

/** Renders the transfer list component. */
export function TransferList({ available, onChange, selected }: InheritedComponentProps<{ available: TransferItem[]; onChange?: (ids: string[]) => void; selected: string[]; }>) { const [marked, setMarked] = useState<string[]>([]); const left = available.filter((item) => !selected.includes(item.id)); const right = available.filter((item) => selected.includes(item.id)); const toggle = (id: string) => setMarked((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); return <View className="gap-3 md:flex-row md:items-center"><TransferColumn items={left} onToggle={toggle} selected={marked} title="Available"/><View className="flex-row justify-center gap-2 md:flex-col"><Pressable className="rounded-xl bg-brand-600 px-4 py-3 web:cursor-pointer" onPress={() => { onChange?.([...new Set([...selected, ...marked])]); setMarked([]); }}><Text className="font-black text-white">→</Text></Pressable><Pressable className="rounded-xl border border-slate-200 px-4 py-3 web:cursor-pointer dark:border-slate-700" onPress={() => { onChange?.(selected.filter((id) => !marked.includes(id))); setMarked([]); }}><Text className="font-black text-slate-700 dark:text-white">←</Text></Pressable></View><TransferColumn items={right} onToggle={toggle} selected={marked} title="Selected"/></View>; } 
/** Renders the reorder list component. */
export function ReorderList({ items, onChange }: InheritedComponentProps<{ items: TransferItem[]; onChange?: (items: TransferItem[]) => void; }>) { const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= items.length) return; const next = [...items]; const current = next[index]; const replacement = next[target]; if (!current || !replacement) return; next[index] = replacement; next[target] = current; onChange?.(next); }; return <View className="overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-700">{items.map((item, index) =><View className="min-h-14 flex-row items-center border-t border-slate-100 px-4 first:border-t-0 dark:border-slate-800" key={item.id}><Text className="mr-3 font-black text-slate-400">≡</Text><Text className="flex-1 font-bold text-slate-700 dark:text-slate-200">{item.label}</Text><Pressable accessibilityLabel={`Move ${item.label} up`} className="p-2 web:cursor-pointer" onPress={() => move(index, -1)}><Text className="font-black text-brand-600 dark:text-brand-300">↑</Text></Pressable><Pressable accessibilityLabel={`Move ${item.label} down`} className="p-2 web:cursor-pointer" onPress={() => move(index, 1)}><Text className="font-black text-brand-600 dark:text-brand-300">↓</Text></Pressable></View>)}</View>; }

/** Renders the infinite list component. */
export function InfiniteList({ items, onLoadMore, renderItem }: InheritedComponentProps<{ items: TransferItem[]; onLoadMore?: () => void; renderItem?: (item: TransferItem) => ReactNode; }>) { return <View className="overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-700">{items.map((item) =><View className="border-t border-slate-100 p-4 first:border-t-0 dark:border-slate-800" key={item.id}>{renderItem?.(item) ?? <Text className="font-semibold text-slate-700 dark:text-slate-200">{item.label}</Text>}</View>)}<Pressable className="min-h-12 items-center justify-center bg-slate-50 web:cursor-pointer dark:bg-slate-800" onPress={onLoadMore}><Text className="font-black text-brand-600 dark:text-brand-300">Load more</Text></Pressable></View>; } 
/** Renders the refreshable content component. */
export function RefreshableContent({ children, onRefresh, refreshing }: InheritedComponentProps<{ children?: ReactNode; onRefresh: () => void; refreshing: boolean; }>) { return <ScrollView className="max-h-72 rounded-2xl border border-slate-200 dark:border-slate-700" contentContainerClassName="p-4" refreshControl={<RefreshControl onRefresh={onRefresh} refreshing={refreshing} tintColor="#5B5CE2"/>}><Text className="mb-3 text-xs font-black uppercase tracking-[1.5px] text-brand-600 dark:text-brand-300">Pull to refresh</Text>{children}</ScrollView>; }
