/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/not-found`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}/tabs${'/(tabs)'}` | `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}/tabs${'/(tabs)'}/tab1` | `/tabs/tab1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}/tabs${'/(tabs)'}/tab2` | `/tabs/tab2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(next)'}/page` | `/page`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/not-found`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(native)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(native)'}/modal` | `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(native)'}/tabs${'/(tabs)'}` | `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(native)'}/tabs${'/(tabs)'}/tab1` | `/tabs/tab1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(native)'}/tabs${'/(tabs)'}/tab2` | `/tabs/tab2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(next)'}/page` | `/page`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/layout${`?${string}` | `#${string}` | ''}` | `/not-found${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(native)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(native)'}/modal${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `${'/(native)'}/tabs${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `${'/(native)'}/tabs${'/(tabs)'}/tab1${`?${string}` | `#${string}` | ''}` | `/tabs/tab1${`?${string}` | `#${string}` | ''}` | `${'/(native)'}/tabs${'/(tabs)'}/tab2${`?${string}` | `#${string}` | ''}` | `/tabs/tab2${`?${string}` | `#${string}` | ''}` | `${'/(next)'}/page${`?${string}` | `#${string}` | ''}` | `/page${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/not-found`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}/tabs${'/(tabs)'}` | `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}/tabs${'/(tabs)'}/tab1` | `/tabs/tab1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(native)'}/tabs${'/(tabs)'}/tab2` | `/tabs/tab2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(next)'}/page` | `/page`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
