'use client'; import type { InheritedComponentProps } from '../types'; 
import { useState } from 'react';
import type { TextInputProps } from 'react-native';
import { Pressable, Text, TextInput, View } from 'react-native';
import { cn } from '../core/cn';
export function SearchBar({ className, onChangeText, value, ...props }: InheritedComponentProps<TextInputProps & { className?: string; }>) { return (<View className={cn('flex-row items-center rounded-2xl border border-slate-200 bg-white px-3 shadow-sm web:transition-all web:duration-200 web:focus-within:border-brand-500 web:focus-within:ring-2 web:focus-within:ring-brand-100 dark:border-slate-700 dark:bg-slate-900 dark:web:focus-within:ring-brand-950', className)}><Text className="mr-2 text-lg font-black text-brand-500">⌕</Text><TextInput accessibilityLabel="Search" className="min-h-12 min-w-0 flex-1 py-3 text-slate-950 web:outline-none dark:text-white" onChangeText={onChangeText} placeholder="Search" placeholderTextColor="#94A3B8" returnKeyType="search" value={value} {...props}/>{value ? <Pressable accessibilityLabel="Clear search" className="p-2 web:cursor-pointer" onPress={() => onChangeText?.('')}><Text className="font-black text-slate-400">×</Text></Pressable> : null}</View>); }
export type NumberFieldProps = InheritedComponentProps<{ className?: string; label?: string; max?: number; min?: number; onChange?: (value: number) => void; step?: number; value: number; }>;
export function NumberField({ className, label, max, min, onChange, step = 1, value }: NumberFieldProps) { const update = (next: number) => onChange?.(Math.min(max ?? next, Math.max(min ?? next, next))); return (<View className={className}>{label ? <Text className="mb-2 text-sm font-bold text-slate-700 dark:text-slate-200">{label}</Text> : null}<View className="flex-row items-center rounded-2xl border border-slate-200 bg-white p-1 shadow-sm dark:border-slate-700 dark:bg-slate-900"><Pressable accessibilityLabel="Decrease value" className="h-10 w-10 items-center justify-center rounded-xl bg-slate-100 active:scale-95 web:cursor-pointer web:transition-colors web:hover:bg-slate-200 dark:bg-slate-800 dark:web:hover:bg-slate-700" onPress={() => update(value - step)}><Text className="text-xl font-black text-slate-700 dark:text-slate-200">−</Text></Pressable><TextInput accessibilityLabel={label ?? 'Number'} className="min-w-20 flex-1 px-3 text-center font-black text-slate-950 web:outline-none dark:text-white" keyboardType="numeric" onChangeText={(text) => { const next = Number(text); if (Number.isFinite(next)) update(next); }} value={String(value)}/><Pressable accessibilityLabel="Increase value" className="h-10 w-10 items-center justify-center rounded-xl bg-brand-600 shadow-sm active:scale-95 web:cursor-pointer web:transition-all web:hover:bg-brand-700 web:hover:shadow-md" onPress={() => update(value + step)}><Text className="text-xl font-black text-white">+</Text></Pressable></View></View>); }
export function PasswordField({ className, ...props }: InheritedComponentProps<TextInputProps & { className?: string; }>) { const [visible, setVisible] = useState(false); return (<View className={cn('flex-row items-center rounded-2xl border border-slate-200 bg-white pr-2 shadow-sm web:transition-all web:focus-within:border-brand-500 web:focus-within:ring-2 web:focus-within:ring-brand-100 dark:border-slate-700 dark:bg-slate-900 dark:web:focus-within:ring-brand-950', className)}><TextInput accessibilityLabel="Password" className="min-h-12 min-w-0 flex-1 px-4 py-3 text-slate-950 web:outline-none dark:text-white" placeholderTextColor="#94A3B8" secureTextEntry={!visible} {...props}/><Pressable accessibilityLabel={visible ? 'Hide password' : 'Show password'} className="rounded-xl px-3 py-2 web:cursor-pointer" onPress={() => setVisible((current) => !current)}><Text className="text-xs font-black uppercase text-brand-600 dark:text-brand-300">{visible ? 'Hide' : 'Show'}</Text></Pressable></View>); }
export function OtpInput({ length = 6, onChange, value }: InheritedComponentProps<{ length?: number; onChange?: (value: string) => void; value: string; }>) { const digits = Array.from({ length }, (_, index) => value[index] ?? ''); return (<View><View className="flex-row gap-2">{digits.map((digit, index) =><View className={cn('h-12 flex-1 items-center justify-center rounded-xl border bg-white dark:bg-slate-900', index === value.length ? 'border-brand-500' : 'border-slate-200 dark:border-slate-700')} key={index}><Text className="text-lg font-black text-slate-950 dark:text-white">{digit || '·'}</Text></View>)}</View><TextInput accessibilityLabel="One-time passcode" className="mt-3 min-h-11 rounded-xl border border-slate-200 bg-slate-50 px-4 text-center tracking-[8px] text-slate-950 web:outline-none dark:border-slate-700 dark:bg-slate-800 dark:text-white" keyboardType="number-pad" maxLength={length} onChangeText={(text) => onChange?.(text.replace(/\D/g, '').slice(0, length))} value={value}/></View>); }
